-- supplier_performance_view.sql
-- Analytical view combining supplier, purchase orders, and delivery metrics

CREATE OR REPLACE VIEW SUPPLIER_PERFORMANCE_VIEW AS
SELECT
  s.SUPPLIER_ID,
  s.NAME,
  s.COUNTRY,
  COUNT(p.PO_ID) AS TOTAL_ORDERS,
  SUM(CASE WHEN d.STATUS = 'ON_TIME' THEN 1 ELSE 0 END) AS ON_TIME_COUNT,
  SUM(CASE WHEN d.STATUS = 'DELAYED' THEN 1 ELSE 0 END) AS DELAYED_COUNT,
  CASE WHEN COUNT(d.DELIVERY_ID)=0 THEN 0 ELSE ROUND(100.0 * SUM(CASE WHEN d.STATUS='ON_TIME' THEN 1 ELSE 0 END)/COUNT(d.DELIVERY_ID),2) END AS ON_TIME_PCT,
  ROUND(AVG(DAYS_BETWEEN(d.EXPECTED_DATE, d.ACTUAL_DATE)),2) AS AVG_DELIVERY_LAG,
  COALESCE(SUM(p.QUANTITY * p.UNIT_PRICE),0) AS TOTAL_SPEND
FROM SUPPLIER s
LEFT JOIN PURCHASE_ORDER p ON p.SUPPLIER_ID = s.SUPPLIER_ID
LEFT JOIN DELIVERY d ON d.PO_ID = p.PO_ID
GROUP BY s.SUPPLIER_ID, s.NAME, s.COUNTRY;
