-- 03_basic_queries.sql
-- Basic queries demonstrating data retrieval and joins

-- List all suppliers
SELECT * FROM SUPPLIER ORDER BY NAME;

-- Total orders per supplier
SELECT s.SUPPLIER_ID, s.NAME, COUNT(p.PO_ID) AS TOTAL_ORDERS, SUM(p.QUANTITY * p.UNIT_PRICE) AS TOTAL_SPEND
FROM SUPPLIER s
LEFT JOIN PURCHASE_ORDER p ON p.SUPPLIER_ID = s.SUPPLIER_ID
GROUP BY s.SUPPLIER_ID, s.NAME
ORDER BY TOTAL_ORDERS DESC;

-- Total procurement cost overall
SELECT SUM(QUANTITY * UNIT_PRICE) AS TOTAL_PROCUREMENT_COST FROM PURCHASE_ORDER;

-- Recent purchase orders (last 30 days sample)
SELECT * FROM PURCHASE_ORDER WHERE ORDER_DATE >= ADD_DAYS(CURRENT_DATE, -30) ORDER BY ORDER_DATE DESC;

-- Join PO with delivery status
SELECT p.PO_ID, p.SUPPLIER_ID, s.NAME, p.ORDER_DATE, d.EXPECTED_DATE, d.ACTUAL_DATE, d.STATUS
FROM PURCHASE_ORDER p
LEFT JOIN DELIVERY d ON d.PO_ID = p.PO_ID
LEFT JOIN SUPPLIER s ON s.SUPPLIER_ID = p.SUPPLIER_ID
ORDER BY p.ORDER_DATE DESC;
