-- 04_analytics_queries.sql
-- Analytics queries: delivery performance, monthly spend, ranking

-- 1) On-time vs Delayed deliveries overall
SELECT
  SUM(CASE WHEN STATUS = 'ON_TIME' THEN 1 ELSE 0 END) AS ON_TIME_COUNT,
  SUM(CASE WHEN STATUS = 'DELAYED' THEN 1 ELSE 0 END) AS DELAYED_COUNT,
  COUNT(*) AS TOTAL_DELIVERIES,
  ROUND(100.0 * SUM(CASE WHEN STATUS = 'ON_TIME' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0),2) AS ON_TIME_PCT
FROM DELIVERY;

-- 2) Supplier delay percentage and counts
SELECT
  s.SUPPLIER_ID,
  s.NAME,
  COUNT(d.DELIVERY_ID) AS TOTAL_DELIVERIES,
  SUM(CASE WHEN d.STATUS = 'DELAYED' THEN 1 ELSE 0 END) AS DELAYED_COUNT,
  ROUND(100.0 * SUM(CASE WHEN d.STATUS = 'DELAYED' THEN 1 ELSE 0 END)/NULLIF(COUNT(d.DELIVERY_ID),0),2) AS DELAY_PCT
FROM SUPPLIER s
LEFT JOIN PURCHASE_ORDER p ON p.SUPPLIER_ID = s.SUPPLIER_ID
LEFT JOIN DELIVERY d ON d.PO_ID = p.PO_ID
GROUP BY s.SUPPLIER_ID, s.NAME
ORDER BY DELAY_PCT DESC NULLS LAST;

-- 3) Monthly procurement spend (by order_date month)
SELECT
  TO_VARCHAR(ORDER_DATE,'YYYY-MM') AS YEAR_MONTH,
  SUM(QUANTITY * UNIT_PRICE) AS MONTHLY_SPEND
FROM PURCHASE_ORDER
GROUP BY TO_VARCHAR(ORDER_DATE,'YYYY-MM')
ORDER BY YEAR_MONTH;

-- 4) Best & worst suppliers by on-time % (require minimum deliveries)
WITH supplier_stats AS (
  SELECT
    s.SUPPLIER_ID,
    s.NAME,
    COUNT(d.DELIVERY_ID) AS DELIVERIES,
    SUM(CASE WHEN d.STATUS = 'ON_TIME' THEN 1 ELSE 0 END) AS ON_TIME
  FROM SUPPLIER s
  LEFT JOIN PURCHASE_ORDER p ON p.SUPPLIER_ID = s.SUPPLIER_ID
  LEFT JOIN DELIVERY d ON d.PO_ID = p.PO_ID
  GROUP BY s.SUPPLIER_ID, s.NAME
)
SELECT SUPPLIER_ID, NAME, DELIVERIES, ON_TIME,
  ROUND(100.0 * ON_TIME/NULLIF(DELIVERIES,0),2) AS ON_TIME_PCT
FROM supplier_stats
WHERE DELIVERIES >= 2
ORDER BY ON_TIME_PCT DESC;

-- 5) Supplier ranking combining on-time % and spend (simple composite)
WITH stats AS (
  SELECT
    s.SUPPLIER_ID,
    s.NAME,
    COUNT(d.DELIVERY_ID) AS DELIVERIES,
    SUM(CASE WHEN d.STATUS = 'ON_TIME' THEN 1 ELSE 0 END) AS ON_TIME,
    SUM(p.QUANTITY * p.UNIT_PRICE) AS TOTAL_SPEND
  FROM SUPPLIER s
  LEFT JOIN PURCHASE_ORDER p ON p.SUPPLIER_ID = s.SUPPLIER_ID
  LEFT JOIN DELIVERY d ON d.PO_ID = p.PO_ID
  GROUP BY s.SUPPLIER_ID, s.NAME
)
SELECT
  SUPPLIER_ID,
  NAME,
  DELIVERIES,
  TOTAL_SPEND,
  ROUND(100.0 * ON_TIME/NULLIF(DELIVERIES,0),2) AS ON_TIME_PCT,
  -- Composite score: 70% on-time pct, 30% inverse spend rank (lower spend preferred)
  RANK() OVER (ORDER BY ROUND(100.0 * ON_TIME/NULLIF(DELIVERIES,0),2) DESC) AS ON_TIME_RANK,
  RANK() OVER (ORDER BY TOTAL_SPEND ASC NULLS LAST) AS SPEND_RANK
FROM stats
ORDER BY ON_TIME_PCT DESC NULLS LAST;
